### ISSUE TITLE
m2r haven't been updated in years

### ISSUE THREAD

**Issue by cblegare** [sphinx-contrib/openapi#123]
With the recent major release Mistune (2.0), leading to breakage (see https://github.com/miyakogi/m2r/issues/66), I suggest to switch to m2r2: https://github.com/CrossNox/m2r2

**Comment by astrojuanlu** [comment]
Or, alternatively, https://myst-parser.readthedocs.io/

**Comment by icemac** [comment]
Using `m2r2` currently does not help either: It also pins `mistune` to version `0.8.4` in its `setup.py`, see https://github.com/CrossNox/m2r2/blob/b47d195275d39201c6bd0da4c26acbae28fcbcb9/setup.py#L24

**Comment by icemac** [comment]
In https://github.com/miyakogi/m2r/issues/60#issuecomment-1103246787 `sphinx-mdinclude` is suggested as an m2r fork which could solve the problem.

**Comment by jeriox** [comment]
@qmonnet just saw that you fixed the issue in a branch of your fork. Any chance you would be willing to maintain that fork any further? would be highly appreciated to have a solution publicly available that does not rely on pinning the mistune version

**Comment by qmonnet** [comment]
> Any chance you would be willing to maintain that fork any further?

Sorry, I don't have the expertise of the time for that (the changes I contributed are pretty minor). But I was planning to submit the changes as a PR to the current repository. It was pending some other fix which was addressed last week, now I just need to find a moment to get to it and create the PR.

**Comment by jeriox** [comment]
> > Any chance you would be willing to maintain that fork any further?
> 
> Sorry, I don't have the expertise of the time for that (the changes I contributed are pretty minor). But I was planning to submit the changes as a PR to the current repository. It was pending some other fix which was addressed last week, now I just need to find a moment to get to it and create the PR.

sad to hear, but understandable. Let's see if something happens to your PR as this repo seems to be untouched for two years...

**Comment by qmonnet** [comment]
@jeriox Just for your information, the PR has been merged, and a new tag was created a few days ago, in case this issue is still relevant to you.

**Comment by jeriox** [comment]
@qmonnet already got the notification that this issue has been closed, was happy to see it. Thanks for the PR and the ping!
