### ISSUE TITLE
0.7.0: `openapi` uses `m2r` which is no longer maintained

### ISSUE THREAD

**Issue by kloczek** [sphinx-contrib/openapi#132]
`m2r` is now marked as archivesd.
This module is no longer maintained and will be not updated for mistune 2.x.
https://github.com/miyakogi/m2r/

**Comment by FriedrichFroebel** [comment]
This has already been reported in #123, as well as an open PR #127 which attempts to fix this.

**Comment by kloczek** [comment]
OK closing.
Taank you.

**Comment by kloczek** [comment]
BTW it is yet another thing which could be put on ToDo list.
Currently in sphinxcontrib/__init__.py is used `pkg_resources` which will be deprecated.
In https://github.com/python/importlib_resources/issues/243 it is possible to find instruction about how to move to `importlib-resources`.

**Comment by FriedrichFroebel** [comment]
This should probably a separate issue then or you might want to fix this in a PR directly.
