### ISSUE TITLE
Fork of openapi till we can get get something merged here again

### ISSUE THREAD

**Issue by phofl** [sphinx-contrib/openapi#135]
Hi, 

I've created a fork of the project for work to fix all the inconsistencies with newer dependency versions. I do not intend to develop new features, only want to keep it maintained and useable. 

Happy to merge PRs if they are sensible and tested if people are interested. Do not intend to do releases right now, personally I am installing from master.

Don't want to take any credit either. Ideally I would like to upstream my changes, but communication with the author stalled.

https://github.com/phofl/openapi

**Comment by georgkrause** [comment]
@phofl this shows an 404, how is the status?

**Comment by phofl** [comment]
Al changes have been merged here as well in the meantime, so I deleted my fork. You can simply use the newest release. Forgot to close the issue.
