### ISSUE TITLE
Superseded documentation reference on statuscode 200

### ISSUE THREAD

**Issue by PhorstenkampFuzzy** [sphinx-contrib/openapi#157]
When clicking on statucode 200 the user is forworded to https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.1.
This documentation says it is Superseded. Could the link be updated?

**Comment by stephenfin** [comment]
That's defined [by sphinxcontrib-httpdomain](https://github.com/sphinx-contrib/httpdomain/blob/005bbbb7ab32069b7adb6020a2ddf7b84969762c/sphinxcontrib/httpdomain.py#L64) which we just use. You probably want to report this there.
