### ISSUE TITLE
Display openapi Schema object in generated sphinx documentation

### ISSUE THREAD

**Issue by Maillol** [sphinx-contrib/openapi#21]
Implemented here: https://github.com/ikalnytskyi/sphinxcontrib-openapi/pull/20

You can see an example of documentation generated here:
https://asterios.readthedocs.io/en/new-api/api.html#post--game-config
Using this openapi.yml file:
https://github.com/Maillol/asterios/blob/new-api/spec/openapi.yml

Note:
 * The shema is displayed for all request. perhaps is better if this behavior is optional.
 * We cannot display shema for each response type because sphinx http domain merges all shema so I display only shema of success response.

**Comment by stephenfin** [comment]
I'm guessing this is resolved in #22. If not, could you update the links to illustrate what it is you're missing? Thanks!
