### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by stephenfin** [sphinx-contrib/openapi#24]
I'd like to use the OpenAPI 3.0.0 support in one of my projects. Any chance we could get a 0.4/1.0 release so I can do so? I guess #16 could go in first, though some rework seems necessary there first.

**Comment by ikalnytskyi** [comment]
@stephenfin I'm going to work on this this week. Before we do so, could you please approve a Travis-CI GitHub App request I sent to sphinx-contrib organization? Apparently, I cannot enable Travis CI for this repo.

**Comment by ikalnytskyi** [comment]
Apparently generating examples for OpenAPI v3.0 is broken, and even *fails* the whole build. I'll work on a fix, and since this logic is not trivial, I'm going to make it optional.

**Comment by stephenfin** [comment]
> @stephenfin I'm going to work on this this week. Before we do so, could you please approve a Travis-CI GitHub App request I sent to sphinx-contrib organization? Apparently, I cannot enable Travis CI for this repo.

Yup, I think I've approved all these requests. Let me know if anything else is needed.

> Apparently generating examples for OpenAPI v3.0 is broken, and even _fails_ the whole build. I'll work on a fix, and since this logic is not trivial, I'm going to make it optiona

Oh? Anything in particular? I can also take a look, if it would help.

**Comment by ikalnytskyi** [comment]
@stephenfin thanks! you can run tests from https://github.com/sphinx-contrib/openapi/pull/28

I do believe that one problem is that `type` is optional in `schema`, and if it's omitted we need to behave as it's `"type": "object"`. Currently we fail with `KeyError`.

**Comment by stephenfin** [comment]
Any updates here? Looks like the issues you were referring to have been resolved

**Comment by ikalnytskyi** [comment]
Deployed! https://pypi.org/project/sphinxcontrib-openapi/
