### ISSUE TITLE
Markdown should be converted to reStructuredText

### ISSUE THREAD

**Issue by stephenfin** [sphinx-contrib/openapi#32]
Multiple fields support CommonMark. We should convert that to rST, perhaps using something like reCommonMark

**Comment by bokysan** [comment]
I'm also facing this issue.

Description of our methods is in Markdown and this gets rendered nicely through redoc but produces strange results when using `sphinxcontrib.openapi`. Even more -- some markdown includes HTML tags and these get escaped when rendering with `sphinxcontrib.openapi`.

As Sphinx already provides support for Markdown, would a simple solution of creating custom files for every description and then just doing `.. include: description.md` work? This does mean that you need to configure your `conf.py` to support Markdown, but that does seem like a reasonable trade-off?

**Comment by stephenfin** [comment]
Not a bad idea. I'd been making things a little more complicated and using `recommonmark` to convert the Markdown to docutils nodes, but doing so would necessitate generating these instead of rst throughout the extensions. If we went the route you were suggesting, I'd imagine this could be hidden behind another flag?

**Comment by bokysan** [comment]
Yeah, you could just specify "my openApi is in markdown" and then the code generation would act a bit differently.

**Comment by nedbat** [comment]
Has there been any progress on this?  Can I help in some way?  I would love to have docs that work both as live Open API docs (which needs markdown), and as static docs on ReadTheDocs.

**Comment by ikalnytskyi** [comment]
@nedbat thanks for making this happen. :+1: Closing now.

**Comment by TBBle** [comment]
I was very confused by this bug report. In case anyone else was confused, markdown support was implemented in #32, see https://sphinxcontrib-openapi.readthedocs.io/#options

Despite Markdown being specified in the OpenAPI specs, RST is the default.

**Comment by ikalnytskyi** [comment]
@TBBle Yeah, sorry about that. I just wanted to be backward compatible. The default will be changed with some major version bump.
