### ISSUE TITLE
"$ref" sections are not rendered at all even if they are defined in the same file.

### ISSUE THREAD

**Issue by zmostaani** [sphinx-contrib/openapi#51]
I am using sphinx to render the `openapi.yml` file given in the documentation of the package, but in the output there is no section **Response JSON Object** that is corresponding to the **$ref** defined in the yaml file. I have tried with other yaml files as well but it is the same for all of them.  I googled the issue as well but I could not find any answer. Now I am wondering is it a bug with openapi or am I missing something?

I am following the documentation step by step meaning:
- added the given example yaml file to a directory named `specs/openapi.yml`
- added this line to my .rst file: `.. openapi:: specs/openapi.yml`
- ran sphinx-build command as usual

I am using the latest version of the required packages:
sphinxcontrib-openapi: 0.4.0
sphinxcontrib-httpdomain: 1.7.0
pyyaml: 5.1.2
jsonschema: 3.0.2
python: 3.6.9

**Comment by ikalnytskyi** [comment]
Hey @zmostaani! Thanks for the feedback, do you use OpenAPI spec v2 or v3?

**Comment by zmostaani** [comment]
Hello, Thank you for your reply.

I am using the exact same example given in the documentation. It starts with `swagger: "2.0"` (my own yaml file starts the same), so I assume I am using OAS 2.0. 

Is there any other way for  me to check what version of OAS I am using?

Thank you.

**Comment by tuffnatty** [comment]
I am also experiencing this problem with a 2.0 spec.

**Comment by tuffnatty** [comment]
@zmostaani It seems the support for response schema rendering has not been released yet. Release 4.0 is too old, for me, installing from git fixed the problem:
```pip install git+https://github.com/sphinx-contrib/openapi.git```

**Comment by zmostaani** [comment]
@tuffnatty Thank you for your reply. Indeed when I installed from git the response object rendered correctly.

Do you think it will be included in the next release and if so when do you think there will be a new release?

**Comment by tuffnatty** [comment]
@zmostaani I suppose it's rather a question for @ikalnytskyi .

**Comment by ikalnytskyi** [comment]
Initially I wanted to do some internal refactoring before making new release. Yet, if there're some annoying bugs, I see no reasons why I shouldn't make a new release right now.

**Comment by ikalnytskyi** [comment]
@zmostaani @tuffnatty I released new version

https://pypi.org/project/sphinxcontrib-openapi/0.5.0/ 

Can you guys please confirm it works for you?

**Comment by zmostaani** [comment]
@ ikalnytskyi Thanks for the work. I installed the new version and it worked fine for me.
