### ISSUE TITLE
[feature request]: support filter by not only  path but also request method

### ISSUE THREAD

**Issue by Trim21** [sphinx-contrib/openapi#59]

**Comment by prestomation** [comment]
Similar ask here. I have an API that models all OPTIONS requests for CORS, but I don't want them in the API document, so an exclude by request method option would be awesome

**Comment by ikalnytskyi** [comment]
https://github.com/sphinx-contrib/openapi/pull/78
https://github.com/sphinx-contrib/openapi/pull/64
