### ISSUE TITLE
Release 0.6.0 with include and exclude

### ISSUE THREAD

**Issue by kdmccormick** [sphinx-contrib/openapi#66]
https://github.com/sphinx-contrib/openapi/pull/56, which adds support for the `include` and `exclude` options, was merged about a month ago, but hasn't been released. The feature has been very useful in our project, so we've been working off of a GitHub pin of the commit. A point release (or patch, whatever works) would be appreciated. Thanks!

**Comment by ikalnytskyi** [comment]
Sorry for the delay. I just released new version. https://pypi.org/project/sphinxcontrib-openapi/0.6.0/
