### ISSUE TITLE
YAML 'merge' keys cause parsing failures

### ISSUE THREAD

**Issue by kpfleming** [sphinx-contrib/openapi#82]
https://github.com/sphinx-contrib/openapi/blob/547f6453753b9d7accb30fa8d1eee2b8e02ebc0d/sphinxcontrib/openapi/utils.py#L39

The constructor for DEFAULT_MAPPING_TAG linked above causes PyYAML to fail to support YAML ['merge keys'](https://yaml.org/type/merge.html). Commenting out this constructor solves the problem, but presumably would cause other problems.

I've looked a bit into the PyYAML code but I'm not able to figure out what a potential solution might be.

**Comment by ikalnytskyi** [comment]
Current master supports Python 3.6  and greater. This version does not require hacking `PyYaml` in order to preserve order, since dictionaries are ordered out of box. So the fix will be simply remove that construction. Thanks for reporting, @kpfleming!
